name: publish-website

on:
  # Trigger the workflow on push to main branch
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    uses: ProjectPythia/cookbook-actions/.github/workflows/build-book.yaml@main
    with:
      environment_file: 'website/environment.yml'
      environment_name: causaldynamics-docs-env
      path_to_notebooks: 'website'
      build_command: 'cp -r ../README.md ../docs ../notebooks .; jupyter-book build .'
      # this is a bit hacky, but the only way to 'inject' a shell command before the build. 
      output_path: '_build/html'
  deploy:
    needs: build
    uses: ProjectPythia/cookbook-actions/.github/workflows/deploy-book.yaml@main
    with:
      publish_dir: "website/_build/html"
